"use client";

import { motion } from "framer-motion";
import { ArrowRight } from "lucide-react";
import { useLanguage } from "@/context/LanguageContext";
import { socials } from "@/data/portfolio";

const content = {
  fr: {
    badge: "Étude de cas phare",
    title1: "Plateforme intelligente de",
    title2: "détection et réponse aux menaces",
    subtitle: "Wazuh + Intelligence Artificielle + Threat Intelligence",
    problemHeading: "Le Problème",
    problems: [
      "Volume important de logs générés par les différentes sources (pare-feux, IDS/IPS, serveurs, endpoints).",
      "Difficulté de corrélation entre des événements provenant de systèmes hétérogènes.",
      "Détection manuelle chronophage et sujette à l'erreur humaine.",
      "Besoin d'enrichissement contextuel via des sources de Threat Intelligence externes.",
      "Absence d'automatisation dans la réponse aux incidents détectés.",
    ],
    architectureHeading: "Architecture",
    architectureSteps: [
      "ATTAQUANT (Kali Linux)",
      "Laboratoire d'entreprise — Windows / Linux / Active Directory",
      "WAZUH SIEM",
      "Threat Intelligence · IA · Analytique",
      "Moteur de décision",
      "Réponse automatisée (Active Response)",
      "Rapport SOC",
    ],
    technologiesHeading: "Technologies",
    resultsHeading: "Résultats",
    resultsText:
      "Le taux de détection est passé de 0 % à 75 % durant les scénarios évalués, suite au déploiement des agents Wazuh et à l'intégration d'une analyse basée sur l'IA, sur 12 techniques MITRE ATT&CK simulées en environnement de laboratoire.",
    linkText: "Voir le laboratoire complet",
    reportLink: "Consulter le mémoire complet (PDF)",
  },
  en: {
    badge: "Featured Case Study",
    title1: "Intelligent Threat Detection",
    title2: "& Response Platform",
    subtitle: "Wazuh + Artificial Intelligence + Threat Intelligence",
    problemHeading: "The Problem",
    problems: [
      "High volume of logs generated by multiple sources (firewalls, IDS/IPS, servers, endpoints).",
      "Difficulty correlating events across heterogeneous systems.",
      "Manual detection is time-consuming and error-prone.",
      "Need for contextual enrichment through external Threat Intelligence sources.",
      "Lack of automation in the response to detected incidents.",
    ],
    architectureHeading: "Architecture",
    architectureSteps: [
      "ATTACKER (Kali Linux)",
      "Enterprise Lab — Windows / Linux / Active Directory",
      "WAZUH SIEM",
      "Threat Intel · AI · Analytics",
      "Decision Engine",
      "Active Response",
      "SOC Reporting",
    ],
    technologiesHeading: "Technologies",
    resultsHeading: "Results",
    resultsText:
      "Detection rate improved from 0% to 75% during the evaluated scenarios, following the deployment of Wazuh agents and the integration of AI-based analysis across 12 simulated MITRE ATT&CK techniques in a laboratory environment.",
    linkText: "View full lab environment",
    reportLink: "Read the full thesis (PDF)",
  },
};

const technologies = [
  "Wazuh",
  "OpenSearch",
  "Python",
  "Machine Learning",
  "LLaMA",
  "Groq",
  "VirusTotal",
  "AbuseIPDB",
  "AlienVault OTX",
  "MITRE ATT&CK",
  "VMware",
  "Windows Server",
  "Ubuntu",
  "Kali Linux",
];

export default function CaseStudy() {
  const { language } = useLanguage();
  const t = content[language];

  return (
    <section id="projects" className="border-t border-[var(--border-color)] px-6 py-28">
      <div className="mx-auto max-w-6xl">
        {/* Header */}
        <div className="mb-14 text-center">
          <span className="inline-block rounded-full border border-[var(--primary)]/30 bg-[var(--primary)]/10 px-4 py-1.5 text-xs font-semibold uppercase tracking-wide text-[var(--secondary)]">
            {t.badge}
          </span>
          <h2 className="mt-5 text-4xl font-bold text-[var(--text)] sm:text-5xl">
            {t.title1}
            <span className="text-[var(--secondary)]"> {t.title2}</span>
          </h2>
          <p className="mt-3 text-sm font-semibold uppercase tracking-[0.2em] text-[var(--muted)]">
            {t.subtitle}
          </p>
        </div>

        {/* Problem */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-14 rounded-2xl border border-[var(--border-color)] bg-[var(--surface)]/40 p-8"
        >
          <h3 className="mb-4 text-lg font-semibold text-[var(--text)]">
            {t.problemHeading}
          </h3>
          <ul className="grid gap-3 sm:grid-cols-2">
            {t.problems.map((p, i) => (
              <li key={i} className="flex gap-3 text-sm leading-6 text-[var(--muted)]">
                <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--critical)]" />
                {p}
              </li>
            ))}
          </ul>
        </motion.div>

        {/* Architecture */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-14"
        >
          <h3 className="mb-6 text-center text-lg font-semibold text-[var(--text)]">
            {t.architectureHeading}
          </h3>
          <div className="mx-auto flex max-w-md flex-col items-center gap-2">
            {t.architectureSteps.map((step, i) => (
              <div key={step} className="flex w-full flex-col items-center">
                <div className="w-full rounded-xl border border-[var(--border-color)] bg-[var(--background)] px-5 py-3 text-center text-sm font-medium text-[var(--text)] shadow-sm">
                  {step}
                </div>
                {i < t.architectureSteps.length - 1 && (
                  <span className="my-1 text-[var(--muted)]">↓</span>
                )}
              </div>
            ))}
          </div>
        </motion.div>

        {/* Technologies */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-14"
        >
          <h3 className="mb-5 text-center text-lg font-semibold text-[var(--text)]">
            {t.technologiesHeading}
          </h3>
          <div className="flex flex-wrap justify-center gap-3">
            {technologies.map((tech) => (
              <span
                key={tech}
                className="rounded-full border border-[var(--border-color)] bg-[var(--surface)]/50 px-4 py-2 text-sm text-[var(--muted)]"
              >
                {tech}
              </span>
            ))}
          </div>
        </motion.div>

        {/* Results */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="rounded-2xl border border-[var(--border-color)] bg-[var(--surface)]/40 p-8"
        >
          <h3 className="mb-5 text-lg font-semibold text-[var(--text)]">
            {t.resultsHeading}
          </h3>

          <div className="mb-2 flex justify-between text-xs text-[var(--muted)]">
            <span>{language === "fr" ? "Initial : 0%" : "Initial: 0%"}</span>
            <span className="font-semibold text-[var(--secondary)]">
              {language === "fr" ? "Résultat : 75%" : "Result: 75%"}
            </span>
          </div>
          <div className="h-3 overflow-hidden rounded-full bg-white/5">
            <motion.div
              initial={{ width: 0 }}
              whileInView={{ width: "75%" }}
              viewport={{ once: true }}
              transition={{ duration: 1.5 }}
              className="h-full rounded-full bg-[var(--secondary)]"
            />
          </div>

          <p className="mt-4 text-sm leading-6 text-[var(--muted)]">
            {t.resultsText}
          </p>

          <a
            href="#labs"
            className="mt-6 inline-flex items-center gap-2 font-semibold text-[var(--secondary)] transition hover:text-[var(--text)]"
          >
            {t.linkText}
            <ArrowRight size={18} />
          </a>
          <a       
            href="#labs"
            className="mt-6 inline-flex items-center gap-2 font-semibold text-[var(--secondary)] transition hover:text-[var(--text)]"
          >
            {t.linkText}
            <ArrowRight size={18} />
          </a>

          <a
            href={socials.report}
            target="_blank"
            rel="noopener noreferrer"
            className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-[var(--muted)] transition hover:text-[var(--secondary)]"
          >
            {t.reportLink}
            <ArrowRight size={16} />
          </a>
        </motion.div>
      </div>
    </section>
  );
}